### ISSUE TITLE
remote_file_list issues

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysat#348]
**Describe the bug**

remote_file_list is not working as expected.

**To Reproduce**
1. Create a NASA CDAWeb instrument
2. rpa = pysat.Instrument(platform='de2', name='rpa')
3. rpa.remote_file_list()
5. Similarly, rpa.remote_file_list(year=1983) doesn't work.

UnboundLocalErrorTraceback (most recent call last)
<ipython-input-11-5cc467409375> in <module>()
----> 1 rpa.remote_file_list()

/Users/russellstoneback/git/pysat/pysat/_instrument.pyc in remote_file_list(self, year, month, day)
   1454 
   1455         return self._list_remote_rtn(self.tag, self.sat_id,
-> 1456                                      year=year, month=month, day=day)
   1457 
   1458     def remote_date_range(self, year=None, month=None, day=None):
/Users/russellstoneback/git/pysat/pysat/instruments/methods/nasa_cdaweb.pyc in list_remote_files(tag, sat_id, remote_site, supported_tags, user, password, fake_daily_files_from_monthly, two_digit_year_break, delimiter, year, month, day)
    527                 mask = mask & (stored_list.index.day == day)
    528 
--> 529     return stored_list[mask]

UnboundLocalError: local variable 'mask' referenced before assignment 

rpa.remote_file_list(year=1983)

AttributeErrorTraceback (most recent call last)
<ipython-input-13-81ceeca92942> in <module>()
----> 1 rpa.remote_file_list(year=1983)

/Users/russellstoneback/git/pysat/pysat/_instrument.pyc in remote_file_list(self, year, month, day)
   1454 
   1455         return self._list_remote_rtn(self.tag, self.sat_id,
-> 1456                                      year=year, month=month, day=day)
   1457 
   1458     def remote_date_range(self, year=None, month=None, day=None):
/Users/russellstoneback/git/pysat/pysat/instruments/methods/nasa_cdaweb.pyc in list_remote_files(tag, sat_id, remote_site, supported_tags, user, password, fake_daily_files_from_monthly, two_digit_year_break, delimiter, year, month, day)
    521     # Downselect to user-specified dates, if needed
    522     if year is not None:
--> 523         mask = (stored_list.index.year == year)
    524         if month is not None:
    525             mask = mask & (stored_list.index.month == month)
AttributeError: 'Index' object has no attribute 'year' 

**Expected behavior**
a list of all remote files.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.12.6, python 2.7

**Additional context**

**Comment by jklenzing** [comment]
Confirmed these errors for python 3.7.3 as well.  Working fine on timed_saber, which was the primary driver when developing this version of the code.  Will look into it.

**Comment by jklenzing** [comment]
Cause of the bug located.  Fixes in place, undergoing unit testing now.

Changes introduced in #238 to improve the location of remote files were compatible with some types of files, but not others.  Essentially, the remote routine looks for two matching parameters when identifying a remote file of the name pattern 'cnofs_cindi_ivm_500ms_{year:4d}{month:02d}{day:02d}_v01.cdf':
1) the file extension, ie '.cdf'
2) the preamble (the bit before the first wildcard or variable signifier), ie 'cnofs_cindi_ivm_500ms_'

Before this pull, only the extension was needed.  However, some data sources store multiple data products in the same directory.  The preamble was added so that `remote_file_list` would only return the specified data product.

The bug affects instruments whose file names only return one type of wildcard/variable character (here defined as '{', '?', and '*').  Those with two or three perform as expected.  The instruments that require this as part of the download routine were not affected, as they should fall into the second category.

Looking into unit tests to catch this sort of thing in the future.

**Comment by jklenzing** [comment]
Implementing unit tests here is more complicated due to use of `remote_file_list` throughout.  Since instrument tests need to be rewritten as part of #327, migrating unit test disucssion there.

**Comment by jklenzing** [comment]
Closed with merge of #354 and #355.
